# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'auth_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uth_service.proto\x12\x0c\x61uthenticate\"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1b\n\x0c\x41uthResponse\x12\x0b\n\x03JWS\x18\x01 \x01(\t\"\x1e\n\x0fValidateRequest\x12\x0b\n\x03JWS\x18\x01 \x01(\t\"#\n\x10ValidateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x11InvalidateRequest\x12\x0b\n\x03JWS\x18\x01 \x01(\t\"%\n\x12InvalidateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xf6\x01\n\x0b\x41uthService\x12G\n\x0c\x41uthenticate\x12\x19.authenticate.AuthRequest\x1a\x1a.authenticate.AuthResponse\"\x00\x12K\n\x08Validate\x12\x1d.authenticate.ValidateRequest\x1a\x1e.authenticate.ValidateResponse\"\x00\x12Q\n\nInvalidate\x12\x1f.authenticate.InvalidateRequest\x1a .authenticate.InvalidateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=36
  _globals['_AUTHREQUEST']._serialized_end=85
  _globals['_AUTHRESPONSE']._serialized_start=87
  _globals['_AUTHRESPONSE']._serialized_end=114
  _globals['_VALIDATEREQUEST']._serialized_start=116
  _globals['_VALIDATEREQUEST']._serialized_end=146
  _globals['_VALIDATERESPONSE']._serialized_start=148
  _globals['_VALIDATERESPONSE']._serialized_end=183
  _globals['_INVALIDATEREQUEST']._serialized_start=185
  _globals['_INVALIDATEREQUEST']._serialized_end=217
  _globals['_INVALIDATERESPONSE']._serialized_start=219
  _globals['_INVALIDATERESPONSE']._serialized_end=256
  _globals['_AUTHSERVICE']._serialized_start=259
  _globals['_AUTHSERVICE']._serialized_end=505
# @@protoc_insertion_point(module_scope)
